runs:
  using: "composite"
  steps:
    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: install dependencies
      run: npm ci
      shell: bash
    - name: storybook build
      run: npm run build-storybook
      shell: bash
    - name: storybook test
      run: npm run test-storybook:ci
      shell: bash
