inputs:
  G_TOKEN:
    description: "github token"
    required: true
  CHROMATIC_PROJECT_TOKEN:
    description: "chromatic token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Move MSW file
      run: mv public/mockServiceWorker.js storybook-static
      shell: bash
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ inputs.G_TOKEN }}
        projectToken: ${{ inputs.CHROMATIC_PROJECT_TOKEN }}
        storybookBuildDir: storybook-static
