name: build

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: 'Create env file'
        shell: bash
        run: |
          touch .env
          echo GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" >> .env
          echo GCP_CLIENT_EMAIL="${{ secrets.GCP_CLIENT_EMAIL }}" >> .env
          cat .env
      - name: Build
        run: npm run build
