name: build

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: 'Create env file'
        shell: bash
        run: |
          touch .env
          echo GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" >> .env
          echo GCP_CLIENT_EMAIL="${{ secrets.GCP_CLIENT_EMAIL }}" >> .env
          echo GCP_PRIVATE_KEY="${{ secrets.GCP_PRIVATE_KEY }}" >> .env
          echo GCP_PRIVATE_KEY_ID="${{ secrets.GCP_PRIVATE_KEY_ID }}" >> .env
          echo X_API_KEY="${{ secrets.X_API_KEY }}" >> .env
          echo NEXT_PUBLIC_FIREBASE_API_KEY="${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env
          echo NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo NEXT_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
          echo NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo NEXT_PUBLIC_FIREBASE_APP_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env
          echo DEV_FIRESTORE_COLLECTION="${{ secrets.DEV_FIRESTORE_COLLECTION }}" >> .env
      - name: Build
        run: npm run build
