name: chromatic_pr_on_push

on: pull_request

jobs:
  chromatic_pr_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr-details
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          DETAILS=$(gh pr view $PR_NUMBER --json labels,state -q '{ "labels": .labels.nodes[].name, "isDraft": .isDraft }' || echo '{ "labels": [""], "isDraft": false }')
          echo "::set-output name=details::$DETAILS"
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
      - name: Conditional step
        run: echo "This step is not skipped."
        if: ${{ !(contains(fromJson(steps.pr-details.outputs.details).labels, 'renovate') || fromJson(steps.pr-details.outputs.details).isDraft) }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: StorybookTest
        uses: ./.github/actions/storybook_test
      - name: Chromatic
        uses: ./.github/actions/chromatic
        with:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
